version: '3.8'

services:
  api-gateway:
    build: .
    volumes:
      - api-gateway-data-v1:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"

  sidecar:
    build: ../sidecar
    volumes:
      - api-gateway-data-v1:/usr/src/app
    depends_on:
      - api-gateway

volumes:
  api-gateway-data-v1: